service: vulnerability-manager

frameworkVersion: '2'
useDotenv: true

package:
  patterns:
    - '!./**'
    - './src/**'

custom:
  tableName: 'vmt-table-${self:provider.stage}'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:BatchGetItem"
            - "dynamodb:ConditionCheckItem"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:Query"
            - "dynamodb:UpdateItem"
          Resource:
            - Fn::GetAtt:
              - VulnerabilityManagerTable
              - Arn
            - Fn::Join:
              - "/"
              - - Fn::GetAtt:
                  - VulnerabilityManagerTable
                  - Arn
                - "index/GSI1"

  environment:
    TABLE_NAME: ${self:custom.tableName}
    STAGE: ${self:provider.stage}
    DEBUG: ${strToBool(${env:DEBUG})}

plugins:
  - serverless-offline

functions:
  listGroups:
    handler: src/handlers/api/groups.get_groups
    events:
      - http:
          path: /groups
          method: get
          request:
            parameters:
              querystrings:
                username: true
  listAssetVulnerabilities:
    handler: src/handlers/api/asset_vulnerabilities.get_asset_vulnerabilities
    events:
      - http:
          path: /asset-vulnerabilities/status-{status}
          method: get
          request:
            parameters:
              paths:
                status: true
              querystrings:
                username: true
                asset: true
  loadTestData:
    handler: src/handlers/load_test_data.load_test_data


resources:
  Resources:
    VulnerabilityManagerTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions: 
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
          - AttributeName: "severity"
            AttributeType: "N"
          - AttributeName: "status"
            AttributeType: "N"
        KeySchema: 
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 5