service: vulnerability-manager

frameworkVersion: '2'
useDotenv: true

package:
  patterns:
    - '!./**'
    - './src/**'

custom:
  tableName: 'vmt-table-${self:provider.stage}'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'

  environment:
    TABLE_NAME: ${self:custom.tableName}
    STAGE: ${self:provider.stage}
    DEBUG: ${strToBool(${env:DEBUG})}

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  loadTestData:
    handler: src/handlers/load_test_data.load_test_data


resources:
  Resources:
    VulnerabilityManagerTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions: 
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
          - AttributeName: "Complexity"
            AttributeType: "N"
          - AttributeName: "Status"
            AttributeType: "N"
        KeySchema: 
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - IndexName: LSI1
            KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: Complexity
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: LSI2
            KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: Status
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: 'GSI1'
            KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "PK"
              KeyType: "RANGE"
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1